config/routes.rb
Rails.application.routes.draw do
  resources :endpoints do
    member do
      get 'subscribe'
      get 'access'
    end
  end

  devise_for :owners
  devise_for :consumers

  get 'pages/index'
  post '/update-rate-limit/:id' => 'pages#update_rate_limit', :as => :update_rate_limit

  

  root to: 'pages#index'
end

app/models/access.rb
class Access < ActiveRecord::Base

  belongs_to :consumer
  belongs_to :endpoint

  validates :consumer_id, presence: true
  validates :endpoint_id, presence: true
  
end

app/models/consumer.rb
class Consumer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :password, confirmation: true
  before_create :set_rate_limit

  has_many :accesses
  has_many :subscriptions

  def subscribed?(endpoint)
    Subscription.where(endpoint_id: endpoint.id, consumer_id: self.id).any?
  end

  def monthly_requests
    self.accesses.group_by{|a| a.created_at.beginning_of_month }.map {|k,v| [k.to_s(:short), v.size] }
  end

  def weekly_requests
    self.accesses.group_by{|a| a.created_at.beginning_of_week }.map {|k,v| [k.to_s(:short), v.size] }
  end

  def daily_requests
    self.accesses.group_by{|a| a.created_at.beginning_of_day }.map {|k,v| [k.to_s(:short), v.size] }
  end

  def today_request_count
    self.accesses.where("created_at >= ?", Time.zone.now.beginning_of_day).count
  end

  def reach_limit?
    today_request_count.to_i > self.rate_limit.to_i
  end

  private
  def set_rate_limit
    self.rate_limit = 1000
  end
end

app/models/endpoint.rb
class Endpoint < ActiveRecord::Base
  belongs_to :owner
  has_many :subscriptions

  validates :title, presence: true
  validates :url, presence: true
  validates :owner_id, presence: true
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :endpoints

  validates :email, presence: true, uniqueness: true
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :endpoint
  belongs_to :consumer

  validates :endpoint_id, presence: true
  validates :consumer_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endpoints_controller.rb
class EndpointsController < ApplicationController
  before_action :set_endpoint, only: [:show, :edit, :update, :destroy, :subscribe, :access]
  before_action :authenticate_owner!, except: [:subscribe, :access]
  before_action :authenticate_consumer!, only: [:subscribe, :access]

  respond_to :html

  def index
    @endpoints = Endpoint.all
    respond_with(@endpoints)
  end

  def show
    respond_with(@endpoint)
  end

  def new
    @endpoint = Endpoint.new
    respond_with(@endpoint)
  end

  def edit
  end

  def create
    @endpoint = Endpoint.new(endpoint_params)
    @endpoint.save
    respond_with(@endpoint)
  end

  def update
    @endpoint.update(endpoint_params)
    respond_with(@endpoint)
  end

  def destroy
    @endpoint.destroy
    respond_with(@endpoint)
  end

  def subscribe
    subscription = Subscription.new(endpoint_id: @endpoint.id, consumer_id: current_consumer.id)
    if subscription.save
      notice = "Subscribed to #{@endpoint.title}"
    else
      noitce = "Failed to subscribe"
    end
    redirect_to root_path, notice: notice
  end

  def access
    access = Access.new(endpoint_id: @endpoint.id, consumer_id: current_consumer.id)
    if !current_consumer.reach_limit? and access.save
      notice = "You were accessed #{@endpoint.title}"
    else
      notice = "Failed to access"
    end
    redirect_to root_path, notice: notice
  end

  private
    def set_endpoint
      @endpoint = Endpoint.find(params[:id])
    end

    def endpoint_params
      params.require(:endpoint).permit(:title, :url, :owner_id, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if consumer_signed_in?
      @endpoints = Endpoint.all
    elsif owner_signed_in?
      @consumers = Consumer.all
    end
  end

  def update_rate_limit
    consumer = Consumer.find(params[:id])
    consumer.rate_limit = params[:rate_limit].to_i
    if consumer.save
      redirect_to :back, notice: 'Rate limit updated'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endpoints_helper.rb
module EndpointsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/endpoints/_form.html.erb
<%= form_for(@endpoint) do |f| %>
  <% if @endpoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@endpoint.errors.count, "error") %> prohibited this endpoint from being saved:</h2>

      <ul>
      <% @endpoint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br>
    <%= f.text_field :owner_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/endpoints/edit.html.erb
<h1>Editing endpoint</h1>

<%= render 'form' %>

<%= link_to 'Show', @endpoint %> |
<%= link_to 'Back', endpoints_path %>

app/views/endpoints/index.html.erb
<h1>Listing endpoints</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Owner</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @endpoints.each do |endpoint| %>
      <tr>
        <td><%= endpoint.title %></td>
        <td><%= endpoint.url %></td>
        <td><%= endpoint.owner.try(:email) %></td>
        <td><%= endpoint.description %></td>
        <td><%= link_to 'Show', endpoint %></td>
        <td><%= link_to 'Edit', edit_endpoint_path(endpoint) %></td>
        <td><%= link_to 'Destroy', endpoint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endpoint', new_endpoint_path %>

app/views/endpoints/new.html.erb
<h1>New endpoint</h1>

<%= render 'form' %>

<%= link_to 'Back', endpoints_path %>

app/views/endpoints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @endpoint.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @endpoint.url %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @endpoint.owner %>
</p>

<p>
  <strong>Description:</strong>
  <%= @endpoint.description %>
</p>

<%= link_to 'Edit', edit_endpoint_path(@endpoint) %> |
<%= link_to 'Back', endpoints_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vanguard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Vanguard</h1>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
</html>

app/views/pages/_consumer.html.erb
    <%= link_to "Logout", destroy_consumer_session_path %>
    <ul>
    <%- for endpoint in @endpoints do %>
      <li>
        <%= endpoint.title %> (<%= endpoint.url %>)
        <%- unless current_consumer.subscribed?(endpoint) %>
        <%= link_to "Subscribe", subscribe_endpoint_path(endpoint) %>
        <%- else %>
        <%= link_to "Access", access_endpoint_path(endpoint) %>
        <%- end %>
      </li>
    <%- end %>
    </ul>

app/views/pages/_owner.html.erb
  <%= link_to "Logout Owner", destroy_owner_session_path %>

  <table>
    <thead>
      <tr>
        <th>Email</th>
        <th>Last Login</th>
        <th>Daily Requests</th>
        <th>Weekly Requests</th>
        <th>Monthly Requests</th>
        <th>Rate Limit</th>
      </tr>
    </thead>

    <tbody>
      <% @consumers.each do |consumer| %>
        <tr>
          <td><%= consumer.email %></td>
          <td><%= consumer.last_sign_in_at %></td>
          <td><%= consumer.daily_requests %></td>
          <td><%= consumer.weekly_requests %></td>
          <td><%= consumer.monthly_requests %></td>
          <td>
            <%= form_tag update_rate_limit_path(consumer.id) do %>
              <%= text_field_tag :rate_limit, consumer.rate_limit %>
              <%= button_tag 'Update' %>
            <%- end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>  

app/views/pages/index.html.erb
<%- if owner_signed_in? %>
  <%= render 'pages/owner' %>
<%- else %>
  <%- if consumer_signed_in? %>
    <%= render 'pages/consumer' %>
  <%- else %>
    <%= link_to "Login", new_consumer_session_path %>
    <%= link_to "Register", new_consumer_registration_path %>
    <br/>
    <br/>
    <%= link_to "Create Owner", new_owner_registration_path %>
    <br/>
    <%= link_to "Owner Login", new_owner_session_path %>
  <%- end %>
<%- end %>